# Generated by Django 4.2.4 on 2023-08-21 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("garagem", "0004_rename_img_veiculo_capa"),
    ]

    operations = [
        migrations.RenameField(
            model_name="modelo",
            old_name="descricao",
            new_name="nome",
        ),
        migrations.RenameField(
            model_name="veiculo",
            old_name="capa",
            new_name="foto",
        ),
        migrations.RemoveField(
            model_name="veiculo",
            name="categoria",
        ),
        migrations.RemoveField(
            model_name="veiculo",
            name="marca",
        ),
        migrations.AddField(
            model_name="modelo",
            name="categoria",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.PROTECT, related_name="veiculos", to="garagem.categoria"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="modelo",
            name="marca",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.PROTECT, related_name="veiculos", to="garagem.marca"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="acessorio",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="categoria",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="cor",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="marca",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="modelo",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="veiculo",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
