# Generated by Django 4.1.7 on 2023-04-28 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', '0004_modelo_alter_veículo_modelo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Acessório',
            new_name='Acessorio',
        ),
        migrations.RenameModel(
            old_name='Veículo',
            new_name='Veiculo',
        ),
        migrations.AlterModelOptions(
            name='cor',
            options={'verbose_name_plural': 'Cores'},
        ),
    ]
