# Generated by Django 4.2.4 on 2023-08-21 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uploader", "0001_initial"),
        ("garagem", "0005_rename_descricao_modelo_nome_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="veiculo",
            name="foto",
        ),
        migrations.AddField(
            model_name="veiculo",
            name="capa",
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name="+", to="uploader.image"),
        ),
    ]
